# Generated by Django 4.2.7 on 2023-11-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marketplace', models.CharField(max_length=255)),
                ('infringing_listing_id', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('type_of_infringement', models.CharField(max_length=255)),
                ('complaint_reason', models.CharField(max_length=255)),
                ('ip_owner', models.CharField(max_length=255)),
                ('registration_number', models.IntegerField()),
                ('additional_information', models.TextField()),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
